[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hedwig"
version = "1.0.0"
description = "AI Email Assistant"
authors = [{name = "Hedwig Team"}]

[tool.pytest.ini_options]
pythonpath = ["src"] 